# Site
name: "Murilo Eduardo"
title: "Blog"
description: "Dicas, artigos e muita coisa bacana sobre Spring e Java de dev pra dev."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
#google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  murilo:
    name: Murilo
    display_name: Murilo Eduardo
    gravatar: 02eb5ac32770f59aa91ddf2fab3e51f4
    email: muriloeduardo1997@outlook.com
    web: http://4solut.com.br
    twitter: http://4solut.com.br
    description: "Crossfiteiro, entusiastas de tecnologias e amante de novas tendências de softwares. Não dispenso uma cervejinha e um bom livro."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
